/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Accounts implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String email;
    private String googleSub;
    private String name;
    private LocalDate dateOfBirth;
    private Integer heightCm;
    private BigDecimal weightKg;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public Accounts() {}

    public Accounts(Accounts value) {
        this.id = value.id;
        this.email = value.email;
        this.googleSub = value.googleSub;
        this.name = value.name;
        this.dateOfBirth = value.dateOfBirth;
        this.heightCm = value.heightCm;
        this.weightKg = value.weightKg;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Accounts(
        UUID id,
        String email,
        String googleSub,
        String name,
        LocalDate dateOfBirth,
        Integer heightCm,
        BigDecimal weightKg,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.email = email;
        this.googleSub = googleSub;
        this.name = name;
        this.dateOfBirth = dateOfBirth;
        this.heightCm = heightCm;
        this.weightKg = weightKg;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.accounts.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.accounts.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.accounts.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.accounts.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.accounts.google_sub</code>.
     */
    public String getGoogleSub() {
        return this.googleSub;
    }

    /**
     * Setter for <code>public.accounts.google_sub</code>.
     */
    public void setGoogleSub(String googleSub) {
        this.googleSub = googleSub;
    }

    /**
     * Getter for <code>public.accounts.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.accounts.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.accounts.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return this.dateOfBirth;
    }

    /**
     * Setter for <code>public.accounts.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * Getter for <code>public.accounts.height_cm</code>.
     */
    public Integer getHeightCm() {
        return this.heightCm;
    }

    /**
     * Setter for <code>public.accounts.height_cm</code>.
     */
    public void setHeightCm(Integer heightCm) {
        this.heightCm = heightCm;
    }

    /**
     * Getter for <code>public.accounts.weight_kg</code>.
     */
    public BigDecimal getWeightKg() {
        return this.weightKg;
    }

    /**
     * Setter for <code>public.accounts.weight_kg</code>.
     */
    public void setWeightKg(BigDecimal weightKg) {
        this.weightKg = weightKg;
    }

    /**
     * Getter for <code>public.accounts.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.accounts.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.accounts.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.accounts.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Accounts other = (Accounts) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.googleSub == null) {
            if (other.googleSub != null)
                return false;
        }
        else if (!this.googleSub.equals(other.googleSub))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.dateOfBirth == null) {
            if (other.dateOfBirth != null)
                return false;
        }
        else if (!this.dateOfBirth.equals(other.dateOfBirth))
            return false;
        if (this.heightCm == null) {
            if (other.heightCm != null)
                return false;
        }
        else if (!this.heightCm.equals(other.heightCm))
            return false;
        if (this.weightKg == null) {
            if (other.weightKg != null)
                return false;
        }
        else if (!this.weightKg.equals(other.weightKg))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.googleSub == null) ? 0 : this.googleSub.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.dateOfBirth == null) ? 0 : this.dateOfBirth.hashCode());
        result = prime * result + ((this.heightCm == null) ? 0 : this.heightCm.hashCode());
        result = prime * result + ((this.weightKg == null) ? 0 : this.weightKg.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Accounts (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(googleSub);
        sb.append(", ").append(name);
        sb.append(", ").append(dateOfBirth);
        sb.append(", ").append(heightCm);
        sb.append(", ").append(weightKg);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
