/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshToken implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private UUID userId;
    private String tokenHash;
    private OffsetDateTime expiresAt;
    private Boolean revoked;
    private OffsetDateTime createdAt;

    public RefreshToken() {}

    public RefreshToken(RefreshToken value) {
        this.id = value.id;
        this.userId = value.userId;
        this.tokenHash = value.tokenHash;
        this.expiresAt = value.expiresAt;
        this.revoked = value.revoked;
        this.createdAt = value.createdAt;
    }

    public RefreshToken(
        UUID id,
        UUID userId,
        String tokenHash,
        OffsetDateTime expiresAt,
        Boolean revoked,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.userId = userId;
        this.tokenHash = tokenHash;
        this.expiresAt = expiresAt;
        this.revoked = revoked;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.refresh_token.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.refresh_token.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.refresh_token.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.refresh_token.user_id</code>.
     */
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.refresh_token.token_hash</code>.
     */
    public String getTokenHash() {
        return this.tokenHash;
    }

    /**
     * Setter for <code>public.refresh_token.token_hash</code>.
     */
    public void setTokenHash(String tokenHash) {
        this.tokenHash = tokenHash;
    }

    /**
     * Getter for <code>public.refresh_token.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Setter for <code>public.refresh_token.expires_at</code>.
     */
    public void setExpiresAt(OffsetDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * Getter for <code>public.refresh_token.revoked</code>.
     */
    public Boolean getRevoked() {
        return this.revoked;
    }

    /**
     * Setter for <code>public.refresh_token.revoked</code>.
     */
    public void setRevoked(Boolean revoked) {
        this.revoked = revoked;
    }

    /**
     * Getter for <code>public.refresh_token.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.refresh_token.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RefreshToken other = (RefreshToken) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.tokenHash == null) {
            if (other.tokenHash != null)
                return false;
        }
        else if (!this.tokenHash.equals(other.tokenHash))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.revoked == null) {
            if (other.revoked != null)
                return false;
        }
        else if (!this.revoked.equals(other.revoked))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.tokenHash == null) ? 0 : this.tokenHash.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.revoked == null) ? 0 : this.revoked.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefreshToken (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(tokenHash);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(revoked);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
