/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq;


import org.example.steptracker.jooq.tables.RefreshToken;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_REFRESH_TOKEN_USER_ID = Internal.createIndex(DSL.name("idx_refresh_token_user_id"), RefreshToken.REFRESH_TOKEN, new OrderField[] { RefreshToken.REFRESH_TOKEN.USER_ID }, false);
}
