/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq;


import org.example.steptracker.jooq.tables.Accounts;
import org.example.steptracker.jooq.tables.RefreshToken;
import org.example.steptracker.jooq.tables.records.AccountsRecord;
import org.example.steptracker.jooq.tables.records.RefreshTokenRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> ACCOUNTS_EMAIL_KEY = Internal.createUniqueKey(Accounts.ACCOUNTS, DSL.name("accounts_email_key"), new TableField[] { Accounts.ACCOUNTS.EMAIL }, true);
    public static final UniqueKey<AccountsRecord> ACCOUNTS_GOOGLE_SUB_KEY = Internal.createUniqueKey(Accounts.ACCOUNTS, DSL.name("accounts_google_sub_key"), new TableField[] { Accounts.ACCOUNTS.GOOGLE_SUB }, true);
    public static final UniqueKey<AccountsRecord> ACCOUNTS_PKEY = Internal.createUniqueKey(Accounts.ACCOUNTS, DSL.name("accounts_pkey"), new TableField[] { Accounts.ACCOUNTS.ID }, true);
    public static final UniqueKey<RefreshTokenRecord> REFRESH_TOKEN_PKEY = Internal.createUniqueKey(RefreshToken.REFRESH_TOKEN, DSL.name("refresh_token_pkey"), new TableField[] { RefreshToken.REFRESH_TOKEN.ID }, true);
    public static final UniqueKey<RefreshTokenRecord> REFRESH_TOKEN_TOKEN_HASH_KEY = Internal.createUniqueKey(RefreshToken.REFRESH_TOKEN, DSL.name("refresh_token_token_hash_key"), new TableField[] { RefreshToken.REFRESH_TOKEN.TOKEN_HASH }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RefreshTokenRecord, AccountsRecord> REFRESH_TOKEN__REFRESH_TOKEN_USER_ID_FKEY = Internal.createForeignKey(RefreshToken.REFRESH_TOKEN, DSL.name("refresh_token_user_id_fkey"), new TableField[] { RefreshToken.REFRESH_TOKEN.USER_ID }, Keys.ACCOUNTS_PKEY, new TableField[] { Accounts.ACCOUNTS.ID }, true);
}
