/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq;


import java.util.Arrays;
import java.util.List;

import org.example.steptracker.jooq.tables.Accounts;
import org.example.steptracker.jooq.tables.RefreshToken;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Accounts.ACCOUNTS,
            RefreshToken.REFRESH_TOKEN
        );
    }
}
