/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq;


import org.example.steptracker.jooq.tables.Accounts;
import org.example.steptracker.jooq.tables.RefreshToken;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public static final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;
}
