/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.example.steptracker.jooq.tables.Accounts;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountsRecord extends UpdatableRecordImpl<AccountsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.accounts.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.accounts.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.accounts.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.accounts.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.accounts.google_sub</code>.
     */
    public void setGoogleSub(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.accounts.google_sub</code>.
     */
    public String getGoogleSub() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.accounts.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.accounts.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.accounts.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.accounts.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.accounts.height_cm</code>.
     */
    public void setHeightCm(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.accounts.height_cm</code>.
     */
    public Integer getHeightCm() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.accounts.weight_kg</code>.
     */
    public void setWeightKg(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.accounts.weight_kg</code>.
     */
    public BigDecimal getWeightKg() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.accounts.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.accounts.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.accounts.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.accounts.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountsRecord
     */
    public AccountsRecord() {
        super(Accounts.ACCOUNTS);
    }

    /**
     * Create a detached, initialised AccountsRecord
     */
    public AccountsRecord(UUID id, String email, String googleSub, String name, LocalDate dateOfBirth, Integer heightCm, BigDecimal weightKg, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Accounts.ACCOUNTS);

        setId(id);
        setEmail(email);
        setGoogleSub(googleSub);
        setName(name);
        setDateOfBirth(dateOfBirth);
        setHeightCm(heightCm);
        setWeightKg(weightKg);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountsRecord
     */
    public AccountsRecord(org.example.steptracker.jooq.tables.pojos.Accounts value) {
        super(Accounts.ACCOUNTS);

        if (value != null) {
            setId(value.getId());
            setEmail(value.getEmail());
            setGoogleSub(value.getGoogleSub());
            setName(value.getName());
            setDateOfBirth(value.getDateOfBirth());
            setHeightCm(value.getHeightCm());
            setWeightKg(value.getWeightKg());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
