/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.example.steptracker.jooq.tables.RefreshToken;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokenRecord extends UpdatableRecordImpl<RefreshTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.refresh_token.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.refresh_token.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.refresh_token.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.refresh_token.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.refresh_token.token_hash</code>.
     */
    public void setTokenHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.refresh_token.token_hash</code>.
     */
    public String getTokenHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.refresh_token.expires_at</code>.
     */
    public void setExpiresAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.refresh_token.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.refresh_token.revoked</code>.
     */
    public void setRevoked(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.refresh_token.revoked</code>.
     */
    public Boolean getRevoked() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.refresh_token.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.refresh_token.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshTokenRecord
     */
    public RefreshTokenRecord() {
        super(RefreshToken.REFRESH_TOKEN);
    }

    /**
     * Create a detached, initialised RefreshTokenRecord
     */
    public RefreshTokenRecord(UUID id, UUID userId, String tokenHash, OffsetDateTime expiresAt, Boolean revoked, OffsetDateTime createdAt) {
        super(RefreshToken.REFRESH_TOKEN);

        setId(id);
        setUserId(userId);
        setTokenHash(tokenHash);
        setExpiresAt(expiresAt);
        setRevoked(revoked);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RefreshTokenRecord
     */
    public RefreshTokenRecord(org.example.steptracker.jooq.tables.pojos.RefreshToken value) {
        super(RefreshToken.REFRESH_TOKEN);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setTokenHash(value.getTokenHash());
            setExpiresAt(value.getExpiresAt());
            setRevoked(value.getRevoked());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
