/*
 * This file is generated by jOOQ.
 */
package org.example.steptracker.jooq.tables;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.example.steptracker.jooq.Keys;
import org.example.steptracker.jooq.Public;
import org.example.steptracker.jooq.tables.RefreshToken.RefreshTokenPath;
import org.example.steptracker.jooq.tables.records.AccountsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Accounts extends TableImpl<AccountsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.accounts</code>
     */
    public static final Accounts ACCOUNTS = new Accounts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountsRecord> getRecordType() {
        return AccountsRecord.class;
    }

    /**
     * The column <code>public.accounts.id</code>.
     */
    public final TableField<AccountsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.accounts.email</code>.
     */
    public final TableField<AccountsRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.accounts.google_sub</code>.
     */
    public final TableField<AccountsRecord, String> GOOGLE_SUB = createField(DSL.name("google_sub"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.accounts.name</code>.
     */
    public final TableField<AccountsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(120), this, "");

    /**
     * The column <code>public.accounts.date_of_birth</code>.
     */
    public final TableField<AccountsRecord, LocalDate> DATE_OF_BIRTH = createField(DSL.name("date_of_birth"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.accounts.height_cm</code>.
     */
    public final TableField<AccountsRecord, Integer> HEIGHT_CM = createField(DSL.name("height_cm"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.accounts.weight_kg</code>.
     */
    public final TableField<AccountsRecord, BigDecimal> WEIGHT_KG = createField(DSL.name("weight_kg"), SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.accounts.created_at</code>.
     */
    public final TableField<AccountsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.accounts.updated_at</code>.
     */
    public final TableField<AccountsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Accounts(Name alias, Table<AccountsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Accounts(Name alias, Table<AccountsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.accounts</code> table reference
     */
    public Accounts(String alias) {
        this(DSL.name(alias), ACCOUNTS);
    }

    /**
     * Create an aliased <code>public.accounts</code> table reference
     */
    public Accounts(Name alias) {
        this(alias, ACCOUNTS);
    }

    /**
     * Create a <code>public.accounts</code> table reference
     */
    public Accounts() {
        this(DSL.name("accounts"), null);
    }

    public <O extends Record> Accounts(Table<O> path, ForeignKey<O, AccountsRecord> childPath, InverseForeignKey<O, AccountsRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountsPath extends Accounts implements Path<AccountsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountsPath(Table<O> path, ForeignKey<O, AccountsRecord> childPath, InverseForeignKey<O, AccountsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountsPath(Name alias, Table<AccountsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountsPath as(String alias) {
            return new AccountsPath(DSL.name(alias), this);
        }

        @Override
        public AccountsPath as(Name alias) {
            return new AccountsPath(alias, this);
        }

        @Override
        public AccountsPath as(Table<?> alias) {
            return new AccountsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AccountsRecord> getPrimaryKey() {
        return Keys.ACCOUNTS_PKEY;
    }

    @Override
    public List<UniqueKey<AccountsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ACCOUNTS_EMAIL_KEY, Keys.ACCOUNTS_GOOGLE_SUB_KEY);
    }

    private transient RefreshTokenPath _refreshToken;

    /**
     * Get the implicit to-many join path to the
     * <code>public.refresh_token</code> table
     */
    public RefreshTokenPath refreshToken() {
        if (_refreshToken == null)
            _refreshToken = new RefreshTokenPath(this, null, Keys.REFRESH_TOKEN__REFRESH_TOKEN_USER_ID_FKEY.getInverseKey());

        return _refreshToken;
    }

    @Override
    public Accounts as(String alias) {
        return new Accounts(DSL.name(alias), this);
    }

    @Override
    public Accounts as(Name alias) {
        return new Accounts(alias, this);
    }

    @Override
    public Accounts as(Table<?> alias) {
        return new Accounts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Accounts rename(String name) {
        return new Accounts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Accounts rename(Name name) {
        return new Accounts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Accounts rename(Table<?> name) {
        return new Accounts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accounts where(Condition condition) {
        return new Accounts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accounts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accounts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accounts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accounts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accounts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accounts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accounts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accounts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accounts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
